# Generated by Django 6.0.2 on 2026-02-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_studentprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
    ]
