# Generated by Django 6.0.2 on 2026-03-01 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscription_last_verified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.university'),
        ),
    ]
