# Generated by Django 6.0.2 on 2026-05-01 19:27

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_studentprofile_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='barcode',
            field=models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Barcode duhet të përmbajë vetëm numra (5-20 shifra).', regex='^\\d{5,20}$')]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificationlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
