# Generated by Django 6.0.2 on 2026-05-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_studentprofile_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='current_qr_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='qr_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
