# Generated by Django 6.0.2 on 2026-05-02 11:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_subscription_current_qr_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryQRToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('hour', models.IntegerField()),
                ('valid_count', models.IntegerField(default=0)),
                ('invalid_count', models.IntegerField(default=0)),
                ('expired_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='current_qr_token',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='qr_token_expires_at',
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['timestamp', 'result'], name='subscriptio_timesta_f365f8_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['controller', 'result', 'timestamp'], name='subscriptio_control_4683cb_idx'),
        ),
        migrations.AddField(
            model_name='temporaryqrtoken',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='subscriptions.subscription'),
        ),
        migrations.AddField(
            model_name='verificationanalytics',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.university'),
        ),
        migrations.AddIndex(
            model_name='temporaryqrtoken',
            index=models.Index(fields=['uuid_token', 'is_used', 'expires_at'], name='subscriptio_uuid_to_7fc583_idx'),
        ),
        migrations.AddIndex(
            model_name='temporaryqrtoken',
            index=models.Index(fields=['subscription', 'is_used', 'expires_at'], name='subscriptio_subscri_a5c4d2_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationanalytics',
            index=models.Index(fields=['date', 'hour'], name='subscriptio_date_64b19d_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationanalytics',
            index=models.Index(fields=['university', 'date'], name='subscriptio_univers_f66dc5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='verificationanalytics',
            unique_together={('date', 'hour', 'university')},
        ),
    ]
