# Generated by Django 6.0.2 on 2026-05-02 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_temporaryqrtoken_verificationanalytics_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryqrtoken',
            name='hashed_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='verificationlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='temporaryqrtoken',
            index=models.Index(fields=['hashed_token', 'is_used', 'expires_at'], name='subscriptio_hashed__64dbf0_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['ip_address', 'result', 'timestamp'], name='subscriptio_ip_addr_bc9b66_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='subscriptio_ip_addr_5533f6_idx'),
        ),
    ]
