# Generated by Django 6.0.2 on 2026-05-03 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_temporaryqrtoken_hashed_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='revocation_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificationanalytics',
            name='revoked_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='verificationlog',
            name='result',
            field=models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], max_length=10),
        ),
    ]
