# Generated by Django 6.0.2 on 2026-05-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_studentprofile_is_revoked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='month',
            field=models.IntegerField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='year',
            field=models.IntegerField(db_index=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['student', 'year', 'month'], name='subscriptio_student_249848_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('student', 'year', 'month'), name='unique_subscription_per_student_per_month'),
        ),
    ]
