# Generated by Django 6.0.2 on 2026-05-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_verificationanalytics_already_used_expired_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationanalytics',
            name='already_used_expired_count',
        ),
        migrations.RemoveField(
            model_name='verificationanalytics',
            name='already_used_valid_count',
        ),
        migrations.AlterField(
            model_name='verificationlog',
            name='result',
            field=models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], max_length=10),
        ),
    ]
