# Generated by Django 6.0.2 on 2026-05-06 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0019_verificationanalytics_already_used_expired_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationanalytics',
            name='already_used_expired_count',
        ),
        migrations.RemoveField(
            model_name='verificationanalytics',
            name='already_used_valid_count',
        ),
    ]
