# Generated by Django 6.0.2 on 2026-05-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0020_remove_verificationanalytics_already_used_expired_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationanalytics',
            name='already_used_expired_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verificationanalytics',
            name='already_used_valid_count',
            field=models.IntegerField(default=0),
        ),
    ]
