# Generated by Django 6.0.2 on 2026-05-16 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0023_alter_verificationlog_sub_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('verification', 'Verifikim QR'), ('subscription_create', 'Krijim abonimi'), ('qr_generate', 'Gjenerim QR'), ('csv_import', 'Import CSV'), ('manual_student_create', 'Shtim manual studenti')], db_index=True, max_length=50)),
                ('duration_ms', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('extra', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['operation', 'timestamp'], name='subscriptio_operati_5ebeae_idx')],
            },
        ),
    ]
